### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'yc_train.npy'

### ISSUE THREAD

**Issue by sujanme25** [hungchun-lin/Stock-price-prediction-using-GAN-Capstone-Group1#2]
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:\Users\sujan\Documents\2020_Papers\Data_Solar\2020_paper1\P5\Stock-price-prediction-using-GAN-Capstone-Group1-master\Code\wgan_gp.py 
Traceback (most recent call last):
  File "C:\Users\sujan\Documents\2020_Papers\Data_Solar\2020_paper1\P5\Stock-price-prediction-using-GAN-Capstone-Group1-master\Code\wgan_gp.py", line 21, in <module>
    yc_train = np.load("yc_train.npy", allow_pickle=True)
  File "C:\Users\sujan\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\lib\npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'yc_train.npy'

**Comment by hungchun-lin** [comment]
@sujanme25 , Please run the "2. data_preprocessing.py" file first, you will get it.
